(
    CHOOSING_DIRECTION,
    CHOOSING_MODEL_CLASS,
    CHOOSING_PREPROCESSING_CLASS,
    CHOOSING_MODEL,
    CODE_EXAMPLE,
    FINAL_CODE_EXAMPLE,
    USER_DATA_LOAD,
    CODE_EXAMPLE_WITH_USER_DATA,
    FINAL_CODE_EXAMPLE_WITH_USER_DATA,
) = range(9)